### ISSUE TITLE
Menubar colour

### ISSUE THREAD

**Issue by cmsethi** [onyx-and-iris/voicemeeter-compact#14]
Thanks for making this app. I have two minor issues.
1) I'm using the black theme,  but not able to change the menu bar color. I have removed the title bar by adding '....overrideredirect(1)' in the navigation file.
2) When the app starts, there is a flash window at the default position as I have changed the position of the window/interface by adding geometry() method that too in the navigation file.
Tried my best to resolve these issues but failed. Please help me to resolve the issues. 
Thanks again, and I look forward to hearing from you.
chander mohan
![vm](https://github.com/onyx-and-iris/voicemeeter-compact/assets/115778294/afb98612-d030-42a0-b7b2-fb97299d00ed)

**Comment by onyx-and-iris** [comment]
Hi. Thanks for checking out the app.

Regarding point 1.
Yes, the background colour of the menu bar when using dark theme is a problem. According to this SO response this issue is [OS related](https://stackoverflow.com/questions/49088785/changing-the-colour-of-tkinter-menubar), due to the fact the menubar is not managed by tkinter.

This isn't the first time I've looked into this issue, however, even changing themes in Windows didn't help so I'm not sure if there is a way to correct this.

If you don't need the VBAN feature you can disable the menu bar altogether since most of the configuration can be set in `app.toml` including layout, extension orientation, user profile configs etc.

Regarding point 2, the flash you describe, I have observed a few things:
- I only notice this when loading the app with Sunvalley Theme. When loading the app with Forest Theme the mainframe renders instantly (although I've only uploaded the light version of that theme).
- However, I think this is partly caused by the fact the GUI renders its labelframes dynamically, according to labelled channels. Therefore, the true composition and orientation of the GUI are unkown until the relevant api calls are made. As well as this, due to using the Grid layout manager, all labelframes are first gridded, then ungridded if they are unlabelled, this is so the Grid manager knows the location of each labelframe, should it later be labelled again. I believe this process is fast but not instant (due to loading the Sunvalley widgets dynamically), and that may contribute to the flash you describe.

Can this be removed? _Perhaps_, (but perhaps not), by reordering how the various frames are gridded but that may have other implications on the code and would need to be done carefully. For example, one thing I tried was to grid_remove() both strip/bus frames from the mainframe (in init_strip() and init_bus()) and then regrid them again at the end of {App}.build_app(), which made the flash appear less obvious (because the size of the mainframe is known by that time), but it was still there. I'm unsure that this problem is big enough to start attempting code surgery to fix it.

If you have any further thoughts to add or you discovered any extra details feel free to respond here.
